mvp/autithi/accounts/urls.py
from django.urls import path
from .views import (
    login_view,
    registration_view,
    logout_view,
)

urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('registration/', registration_view, name="register"),
    
]

mvp/autithi/autithi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='city_list'),
    path('account/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('proparty/', include(('proparty.urls', 'proparty'), namespace='proparty')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mvp/autithi/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous"> -->

<!-- Fontawesome CSS -->
<!-- <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' /> -->

<!-- jquery-confirm CSS -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css"> -->


<!-- Custom Stripe Styling -->
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
<link rel="stylesheet" href="{% static 'css/lightbox.css' %}">
<link rel="stylesheet" href="{% static 'css/slick.css' %}">
<link rel="stylesheet" href="{% static 'css/slick-theme.css' %}">
<link rel="stylesheet" href="{% static 'css/mdb.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">

mvp/autithi/templates/base/forms.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <button type='submit' class='btn btn-default'>Save</button>
</form>
</div>
{% endblock %}

mvp/autithi/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS
slim is missing ajax -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

<!-- Stripe JS -->
<script src="https://js.stripe.com/v3/"></script>


<!-- jquery-confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!-- js Render -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js'></script>
{% include 'base/js_templates.html' %}


<!-- Chart.js -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js'></script>

<!-- Django Secure AJAX JS -->
<script src='{% static "js/csrf.ajax.js" %}'></script>


<script src='{% static "js/jquery-3.4.0.min.js" %}'></script>
<script src='{% static "js/popper.min.js" %}'></script>
<script src='{% static "js/lightbox.js" %}'></script>
<script src='{% static "js/slick.js" %}'></script>
<script src='{% static "js/mdb.js" %}'></script>
<script src='{% static "js/bootstrap.js" %}'></script>
<script src='{% static "js/custom.js" %}'></script>

mvp/autithi/templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form -->
<script id="stripeTemplate" type="text/x-jsrender">
    <form class='payment-form' action="" method="post" id="payment-form" data-token='{{:publishKey}}' data-next-url='{{:nextUrl}}'>
  <div class="form-row">
    <!-- <label for="card-element">
      Credit or debit card
    </label> -->
    <div id="card-element" class='form-control'> 
      <!-- a Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button class='btn btn-primary my-3 btn-load'>{{:btnTitle }}</button>

    </form>

</script>
{% endverbatim %}

mvp/autithi/templates/base/navbar.html
{% url 'city_list' as home_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:register' as register_url %}
<nav class="navbar navbar-expand-md fixed-top scrolling-navbar">
  <a class="navbar-brand" href="{{ home_url }}">
    <img src="//getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    {% if brand_name %} {{brand_name }} {% else %}Autithi {% endif %}

  </a>
  <!-- Button Start -->
  <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
    <div class="container" onclick="myFunction(this)">
      <div class="bar1"></div>
      <div class="bar2"></div>
      <div class="bar3"></div>
    </div>
  </button>
  <!-- Button End -->
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <!-- Search Box Start -->
    <div class="input-group search-box">
      <input class="form-control" type="text" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <span class="input-group-text"><i class="fas fa-search text-grey"></i></span>
      </div>
    </div>
    <!-- Search Box End -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a href="{{ home_url }}" class="nav-link">Home</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Become Host</a>
      </li>

      <!-- Help Start-->
      <li class="nav-item">
        <a href="#" class="nav-link" data-toggle="modal" data-target="#modalContactForm">Help</a>
      </li>
      <form action="">
        <div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

          <div class="modal-dialog" role="document">

            <div class="modal-content">
              <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Write to us</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body mx-3">
                {% if request.user.is_authenticated == False %}
                <div class="md-form mb-5">
                  <i class="fas fa-user prefix grey-text"></i>
                  <input type="text" id="form34" class="form-control validate">
                  <label data-error="wrong" data-success="right" for="form34">Your name</label>
                </div>
                <div class="md-form mb-5">
                  <i class="fas fa-envelope prefix grey-text"></i>
                  <input type="email" id="form29" class="form-control validate">
                  <label data-error="wrong" data-success="right" for="form29">Your email</label>
                </div>
                {% endif %}

                <div class="md-form mb-5">
                  <i class="fas fa-tag prefix grey-text"></i>
                  <input type="text" id="form32" class="form-control validate">
                  <label data-error="wrong" data-success="right" for="form32">Subject</label>
                </div>

                <div class="md-form">
                  <i class="fas fa-pencil prefix grey-text"></i>
                  <textarea type="text" id="form8" class="md-textarea form-control" rows="4"></textarea>
                  <label data-error="wrong" data-success="right" for="form8">Your message</label>
                </div>

              </div>
              <div class="modal-footer d-flex justify-content-center">
                <button class="btn btn-dark">Send <i class="fas fa-paper-plane-o ml-1"></i></button>
              </div>
            </div>


          </div>

        </div>
      </form>
      <!-- Help End -->


      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{ logout_url }}">Log Out</a>
      </li>
      {% else %}
      <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Sign Up</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Log In</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>